# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Test) configuration. ####
#
spring:
  boot: # Spring boot admin.
    admin:
      notify.composite:
        href-url: http://127.0.0.1:${server.port}/${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://${DEVOPS_DB_URL:owner-node1:3306}/devops?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
      username: gzsm
      password: gzsm@%#jh?
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true

# Spring-security config.
security.user:
  name: sba_user
  password: hnGsFm6k0klJP9j

# Redis configuration.
redis:
  passwd: zzx!@#$%
  connect-timeout: 10000
  max-attempts: 10
  # Redis's cluster nodes.
  nodes:
    - owner-node1:6379
    - owner-node1:6380
    - owner-node1:6381
    - owner-node1:7380
    - owner-node1:7380
    - owner-node1:7381

opentsdb:
  url: http://10.0.0.57
  port: 4242