# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### SBA server common configuration. ####
#
# Spring-boot admin server config. http://codecentric.github.io/spring-boot-admin/1.5.3/#spring-boot-admin-server
spring.boot.admin:
  #username: sba_user
  #password: sba_user
  context-path: /sba
  redis-store: # com.wl4g.devops.umc.config.RedisStoreConfiguration
    enabled: true
    application-store: ${spring.cloud.zookeeper.discovery.root}-sba-application-store
    event-store: ${spring.cloud.zookeeper.discovery.root}-sba-event-store
  monitor:
    period: 8000
    status-lifetime: 15000
    connect-timeout: 3000
    read-timeout: 4000
  notify:
    # Disable SBA default mail notification.
    mail.enabled: false
    # Note that when multiple types of notifications are opened, the circular execution notification will
    # be executed synchronously. If the exception is executed before, the latter will not be executed.
    composite:
      # de.codecentric.boot.admin.notify.AbstractEventNotifier.setEnabled()
      enabled: true
      #subject: 安诺信系统服务健康
      subject: 安监云系统服务健康
      fromName: DevOps
      phone-to: 18127978606
      mail-to: 983708408@qq.com
      #mail-to: 983708408@qq.com,171429233@qq.com
      # de.codecentric.boot.admin.notify.AbstractStatusChangeNotifier.ignoreChanges
      #ignore-changes: 
      # State message save time.
      expire-sec: 259200
      #server-url: 
      server-port: ${server.port}
  #routes:
    #endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti

# Management configuration.
management:
  security.enabled: false

# Spring security configuration.
security:
  basic.enabled: false
  user:
    #name: sba_user
    #password: AnGsFmkH2w5lJP9j

# Spring endpoints configuration.
endpoints:
  cors.allowed-methods: HEAD,GET,POST
  health.sensitive: false
  #env.enabled: true
  #info.enabled: true
  #dump.enabled: true
  #heapdump.enabled: true
  #auditevents.enabled: true
  #beans.enabled: true
  #trace.enabled: true
  #metrics.enabled: true
  #loggers.enabled: true
  #docs.enabled: true
  shutdown:
    enabled: true
    sensitive: true # Marked as sensitive.
