# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# #### Spring cloud devops support configuration. ####
#
spring:
  cloud:
    devops:
      #support:
      #  devel:
      #    mybatis-loader: # Mybatis mappers autoloader for development only(Note: production disabled)
      #      enable: false  # Default with: auto(enable jdwp?)
      #      fast-fail: false
      #      monitor-loader-interval-ms: 1000
      #  notification:
      #    mail:
      #      enable: false # Default[false]
      #      host: smtp.sina.com
      #      port: 465
      #      username: safec7782@sina.com
      #      password: safec7782
      #      protocol: smtp
      #      default-encoding: UTF-8
      #      properties:
      #        mail.smtp.auth: true
      #        # Note: that you must display the settings ssl. enable, otherwise SSL is disabled by default in windows,
      #        # but is turned on by default in linux, which will cause inconsistency.
      #        mail.smtp.ssl.enable: true
      #        mail.smtp.timeout: 15000
      #        mail.smtp.starttls.enable: true
      #        mail.smtp.starttls.required: true
      #        #mail.smtp.socketFactory.port: ${spring.mail.port}
      #        #mail.smtp.socketFactory.fallback: false
      #        #mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      #      templates: # http://www.bejson.com/convert/unicode_chinese
      #        tpl1: Application health notification：${appInfo} status changed from ${fromStatus} to ${toStatus}, details：${msg}
      #        tpl2: Your verification code is：${code} valid for 5 minutes. You can't tell anyone if you're dead. Thank you for using!
      #    # Some configuration...
      #    sms:
      #      enable: true # Default[false]
      #      aliyun:
      #        regionId: cn-hangzhou
      #        accessKeyId: LTAI4Fk9pjU7ezN2yVeiffYm
      #        accessKeySecret: {ALIYUN_SECRET}
      #        signName: Super Devops\u7edf\u4e00\u76d1\u63a7\u5e73\u53f0
      #        templates: # https://dysms.console.aliyun.com/dysms.htm#/domestic/text/template
      #          tpl1: SMS_140726862 # Alarm notice template.
      #          tpl2: SMS_109490228 # VerificationCode notice template.
      #    vms:
      #      enable: true # Default[false]
      #      aliyun:
      #        regionId: cn-hangzhou
      #        accessKeyId: LTAI4Fk9pjU7ezN2yVeiffYm
      #        accessKeySecret: {ALIYUN_SECRET}
      #        calledShowNumber: 055162153866
      #        templates:
      #          tpl1: TTS_184825642 # Alarm notice template.
      #          tpl2: TTS_184820765 # VerificationCode notice template.
      #    wechat:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    qq:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    apns:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    bark:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    dingtalk:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    facebook:
      #      enable: false # Default[false]
      #      # Some configuration...
      #    twitter:
      #      enable: false # Default[false]
      #      # Some configuration...
