# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment base configuration. ####
spring:
  application.name: umc-facade
  profiles:
    include: common,support,util,base
    active: dev
  xcloud:
    component:
      support:
        notification:
          mail:
            enable: true # Default[false]
            properties:
              mail.smtp.auth: true
              mail.smtp.ssl.enable: true
              mail.smtp.timeout: 15000
              mail.smtp.starttls.enable: true
              mail.smtp.starttls.required: true
            templates: # http://www.bejson.com/convert/unicode_chinese
              tpl1: Application health notification：${appInfo} status changed from ${fromStatus} to ${toStatus}, details：${msg}
              tpl2: Your verification code is：${code} valid for 5 minutes. You can't tell anyone if you're dead. Thank you for using!
          sms:
            enable: true # Default[false]
            aliyun:
              regionId: cn-hangzhou
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
              signName: XCloud Devops \u7edf\u4e00\u76d1\u63a7\u5e73\u53f0
              templates: # https://dysms.console.aliyun.com/dysms.htm#/domestic/text/template
                tpl1: SMS_140726862 # Alarm notice template.
                tpl2: SMS_109490228 # VerificationCode notice template.
          vms:
            enable: true # Default[false]
            aliyun:
              regionId: cn-hangzhou
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
              calledShowNumber: 055162153866
              templates:
                tpl1: TTS_184825642 # Alarm notice template.
                tpl2: TTS_184820765 # VerificationCode notice template.

# Mybatis configuration.
mybatis:
  configLocation: mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.wl4g.devops.common.bean.*.*

# Logging configuration.
logging:
  file:
    # see:com.wl4g.component.core.logging.logback.EnhancedLogbackConfigurer#apply
    # see:org.springframework.boot.logging.LogFile#toString
    name: ${server.tomcat.basedir}/../log/${spring.application.name}/${spring.application.name}.log
    clean-history-on-start: false
    total-size-cap: 200GB # default to 200GB
    max-size: 1GB # default to 10MB
    max-history: 30 # default to 7
  pattern:
    #console: ${logging.pattern.file}
    #file: '%d{yy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%4p} ${PID} [%t] [%X{_H_:X-Request-ID}] [%X{_H_:X-Request-Seq}] [%X{_C_:${spring.cloud.devops.iam.cookie.name}}] - %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
  root: INFO
  level:
    org:
      springframework: INFO
      apache: INFO
    com:
      wl4g.devops.umc.data: DEBUG

# ### Server configuration. ###
server:
  servlet:
    contextPath: /${spring.application.name}
  #address: 0.0.0.0
  port: 17061
  sessionTimeout: 30
  tomcat:
    uri-encoding: UTF-8
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir: /tmp/${spring.application.name}
    access-log-enabled: false
    accesslog.directory: logs/
    backgroundProcessorDelay: 30 #seconds
    max-thread: 50 # Max worker threads(default:200).
