# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Test) configuration. ####
#
spring:
  cloud:
    devops:
      iam: # IAM configuration.
        cors:
          rules:
            /**:
              allowsOrigins:
                - http://${DEVOPS_DOMAIN_TOP:wl4g.dev}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.dev:${server.port}}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.local}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.local:${server.port}}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.debug}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.debug:${server.port}}
                - http://*.${DEVOPS_DOMAIN_TOP:wl4g.debug}
                - http://*.${DEVOPS_DOMAIN_TOP:wl4g.debug:${server.port}}
                - http://localhost:8080
                - http://localhost:14040
                - http://127.0.0.1:8080
                - http://127.0.0.1:14040
                #- '*'
        login-uri: /view/login.html
        #login-uri: http://localhost:8080/#/login # See: super-devops-view
        unauthorized-uri: /view/403.html
        #success-endpoint: umc-manager@http://localhost:14048/umc-manager
        success-endpoint: ${spring.application.name}@/view/index.html
        acl:
          secure: false # Turn off protection will trust any same intranet IP.
          allowIpRange: ${DEVOPS_IAM_ACL_ALLOW:127.0.0.1}
          denyIpRange: ${DEVOPS_IAM_ACL_DENY}
        captcha:
          #jigsaw:
            #source-dir: ${server.tomcat.basedir}/data/jigsaw-maternal
        sns: # SNS configuration.
          oauth2-connect-expire-ms: 60_000 # oauth2 connect processing expire time
          wechat-mp:
            app-id: yourappid
            app-secret: yoursecret
            redirect-url: https://iam.${DEVOPS_DOMAIN_TOP:wl4g.com}${server.contextPath}/sns/wechatmp/callback
          wechat:
            app-id: yourappid
            app-secret: yoursecret
            redirect-url: http://passport.wl4g.com${server.contextPath}/sns/wechat/callback
            href: https://static.wl4g.com:2443/iam/static/wx.css
          qq:
            app-id: 101542056
            app-secret: 46b2ba9fa24c2b973abc64ec898db3b4
            redirect-url: http://passport.wl4g.com${server.contextPath}/sns/qq/callback
  # Spring datasource configuration.
  datasource:            
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://${DEVOPS_DB_URL:owner-node1:3306}/devops_dev?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
      username: ${DEVOPS_DB_USER:gzsm}
      password: ${DEVOPS_DB_PASSWD:gzsm@%#jh?}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true

# Redis configuration.
redis:
  passwd: ${REDIS_PASSWD:zzx!@#$%}
  connect-timeout: 10000
  max-attempts: 10
  # Redis's cluster nodes.
  nodes: ${REDIS_NODES:owner-node1:6379,owner-node1:6380,owner-node1:6381,owner-node3:6379,owner-node3:6380,owner-node3:6381}
