# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Prod) configuration. ####
#
spring:
  cloud:
    devops:
      iam:
        cors:
          rules:
            /**:
              allowsOrigins:
                - https://${DEVOPS_DOMAIN_TOP:wl4g.com}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.com}
                - https://*.${DEVOPS_DOMAIN_TOP:wl4g.com}
                - http://*.${DEVOPS_DOMAIN_TOP:wl4g.com}
        login-uri: https://devops.${DEVOPS_DOMAIN_TOP:wl4g.com}/#/login
        unauthorized-uri: /view/403.html
        success-endpoint: umc-manager@https://umc.${DEVOPS_DOMAIN_TOP:wl4g.com}/umc-manager
        acl:
          secure: false # Turn off protection will trust any same intranet IP.
          allowIpRange: ${DEVOPS_IAM_ACL_ALLOW:127.0.0.1}
          denyIpRange: ${DEVOPS_IAM_ACL_DENY}
        captcha:
          #jigsaw:
            #source-dir: ${server.tomcat.basedir}/data/jigsaw-maternal
        sns: # SNS configuration.
          oauth2-connect-expire-ms: 60_000 # oauth2 connect processing expire time
          wechat-mp:
            app-id: yourappid
            app-secret: yoursecret
            redirect-url: https://iam.${DEVOPS_DOMAIN_TOP:wl4g.com}${server.contextPath}/sns/wechatmp/callback
          wechat:
            app-id: yourappid
            app-secret: yoursecret
            redirect-url: https://iam.${DEVOPS_DOMAIN_TOP:wl4g.com}${server.contextPath}/sns/wechat/callback
            href: https://${DEVOPS_DOMAIN_TOP:wl4g.com}/${server.contextPath}/view/static/css/wx-1.0.0.css
          qq:
            app-id: 101542056 # Public testing.
            app-secret: 46b2ba9fa24c2b973abc64ec898db3b4
            redirect-url: https://iam.${DEVOPS_DOMAIN_TOP:wl4g.com}{server.contextPath}/sns/qq/callback
  # Spring datasource configuration.
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://${DEVOPS_DB_URL:safecloud-defaulti.mysql.rds.aliyuncs.com:3306}/devops?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${DEVOPS_DB_USER:devops}
      password: ${DEVOPS_DB_PASSWD:DFDDD7F502E694F3E40D750FEEAE423D}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true

# Redis configuration.
redis:
  passwd: ${REDIS_PASSWD:zzx!@#$%}
  connect-timeout: 10000
  max-attempts: 10
  # Redis's cluster nodes.
  nodes: ${DEVOPS_REDIS_NODES:n1.redis-cluster.wl4g.com:6379,n1.redis-cluster.wl4g.com:6380,n1.redis-cluster.wl4g.com:6381,n2.redis-cluster.wl4g.com:6379,n2.redis-cluster.wl4g.com:6380,n2.redis-cluster.wl4g.com:6381}
